### PR TITLE
(Master Feature) Added second schedule code filter and cart count to rdlibrary(1)

### PR DESCRIPTION
**Pull request by deltecent**
Submitted for your approval, I added a second schedule code filter to rdlibrary(1). Events in rdlogmanager(1) supports two schedule codes, but it wasn't possible to see the carts that meet that criteria in rdlibrary(1).

I also added a cart count label that shows the number of matching carts.

I also commented out the note bubble code since it wasn't implemented. My suggestion there is to replace the note bubble with a right-click menu.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
I take it that this is for after the initial production v3.x release?

**Comment by deltecent** [comment]
About that. I said I was off the new feature wagon but I’m hoping this will go into 3.0. I made some changes to our schedule codes and that’s when I noticed the deficiency in rdlibrary, at least for us. I’m fairly confident that the change didn’t break anything else. But whatever you think is best.

**Comment by ElvishArtisan** [comment]
If you're good with it, so am I. 

However, let's not piggyback the Note Bubble stuff into the same PR, as that's a completely unrelated issue. I will be taking a look at it today, as that really does need to work in v3.0.x.

**Comment by deltecent** [comment]
I updated the PR omitting the Note Bubble changes.

**Comment by ElvishArtisan** [comment]
I get a strange '100 Carts Match Filters' string that superimposes itself over the 'Clear' button when the main window is dragged to minimum size, while the 'Show Only First 100 Matches' label is clipped. See attached screen shot.

image

**Comment by deltecent** [comment]
Would it be ok to change the minimum size to something larger?

**Comment by ElvishArtisan** [comment]
Free free to run it up the flagpole with the community on Rivendell-dev. I know of a few sites that still run monitors with 1024x768 max resolution, but this *is* 2019 after all. The fact that we're making a major version change actually make this the ideal time to moot the question.

**Comment by deltecent** [comment]
There's been no response to my query on Rivendell-dev. I assume that means it's ok. If we could put this into 3.0 release, I'd appreciate it. I started using two schedule codes and find it very inconvenient not being able to view them that way in ```rdlibrary```.

**Comment by ElvishArtisan** [comment]
What date did that query go out? I never saw it go by here. Weird...

**Comment by deltecent** [comment]
April 30 at 10:43 PDT.

**Comment by ElvishArtisan** [comment]
The current minimum monitor resolution for Rivendell is 1024x786. As long as you're staying within that size, we should be fine. No Act of Congress required!

I don't know how I got the idea that you were looking to go wider than 1024.

**Comment by ElvishArtisan** [comment]
Ah, I see what you're doing now! This also adds a counter to display how many matches were returned. Nice!

Might I offer a suggestion? The fact that this field actually changes as the filter parameters are altered is getting a little lost in the visual clutter right now (at least, it took me awhile to even notice that it was changing). Could we try formatting actual number of matches so it looks visually different from the label text? For example, instead of:

     90 Carts Match Filters

something like:

    Matching Carts: 90

and have the '90' displayed as a data field? (I find that a ```QLineEdit``` set for read-only works well for these sorts of things. See for example the read-only 'Type:' field in the 'Edit Cart' dialog.)

image

**Comment by deltecent** [comment]
Sure, that looks much better!

Patrick

**Comment by ElvishArtisan** [comment]
Merged to 'master'. Thank you!

**Pull request merged**
