### PR TITLE
UTF8 Problem

### PR DESCRIPTION
**Pull request by workino**
Hello Fred,
i rewrote part of pypad_shoutcast1.py to be compliant with utf8 and also to have the possibility to manage more stream specifying the SID

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
The UTF-8 problems have already been fixed in a529ed4. Unfortunately, Requests escapes spaces (ASCII 0x20) with a '+' rather than '%20'. While this is valid ```application/x-www-form-urlencoded``` encoding, Shoutcast v1.x expects straight percent-encoding. Thus, strings like 'this is a line' end up looking like 'this+is+a+line'. I was not able to find any way to force Requests to use the other encoding, hence, we still use PyCurl and escape the fields manually.

I like the SID support though. Could you work that up into a PR of its own?

**Comment by workino** [comment]
Hello Fred,
the pypad_shoutcast1.py i modified is sending correctly the song name to shoutcast without + any other strange character and i'm escaping also all punctuation at the begging trough  the function strip(string.punctuation).
If you have a little time give it a try and let me know because i have no problem with strange characters in song.
example: 
Playing Now: | Franz Ferdinand - Take Me Out
 
Sorry but what do you mean if i can work into a PR?

Happy to help
Gabriele

**Comment by ElvishArtisan** [comment]
> the pypad_shoutcast1.py i modified is sending correctly the song name to shoutcast without + any other strange character and i'm escaping also all punctuation at the begging trough the function strip(string.punctuation).
> If you have a little time give it a try and let me know because i have no problem with strange characters in song.

Oh, I have! My practice is to test against the latest Shoutcast Linux releases of v1.x (currently v1.9.8) and v2.x (currently v2.6.0.753). v2.6.0.753 works fine with Requests, but v1.9.8 replaces all string spaces with '+'. It's a bug in that Shoutcast version, but unfortunately Requests has no way to work around it.

> Sorry but what do you mean if i can work into a PR?

PR = Pull Request. Sorry for the jargon! :)
In other words, can you put the SID support into a pull request, *without* the Requests changes?

**Comment by workino** [comment]
Hello Fred,
thanks for your explanation. Yes i can create a PR with SID but will  not work with shotcast v2.
I'm trying to configure a v1 server for make some test but i'm getting always bad password :(
This is the command I'm using to lunch glasscoder:
glasscoder --server-type=shout1 --server-url=http://164.132.98.119:8005 --server-auth=:pisolo --audio-format=mp3 --audio-samplerate=48000 --audio-channels=2 --audio-bitrate=128 --stream-name="R-OK" --audio-device=jack --jack-client-name=shout1 --verbose

Server log:
<01/24/20@11:30:08> [main] Client Stream thread [0] starting
<01/24/20@11:30:08> [main] client main thread starting
<01/24/20@11:30:08> [source] listening for connection on port 8006
<01/24/20@11:30:23> [source] connected from 86.49.253.254  
<01/24/20@11:37:51> [sleeping] 0 listeners (0 unique)

**Comment by ElvishArtisan** [comment]
> glasscoder --server-type=shout1 --server-url=http://XXX.XXX.XXX.XXX:8005 --server-auth=:XXX --audio-format=mp3 --audio-samplerate=48000 --audio-channels=2 --audio-bitrate=128 --stream-name="R-OK" --audio-device=jack --jack-client-name=shout1 --verbose

Hmm. That invocation works fine here. (The YP errors are normal, and expected).

*** snip snip ***
<01/24/20@09:35:34> [SHOUTcast] DNAS/Linux v1.9.8 (Feb 28 2007) starting up...
<01/24/20@09:35:34> [main] pid: 2667
<01/24/20@09:35:34> [main] loaded config from /root/shoutcast_v1/shoutcast_configs/sc_serv-6010.conf
<01/24/20@09:35:34> [main] initializing (usermax:32 portbase:6010)...
<01/24/20@09:35:34> [main] No ban file found (sc_serv.ban)
<01/24/20@09:35:34> [main] No rip file found (sc_serv.rip)
<01/24/20@09:35:34> [main] opening source socket
<01/24/20@09:35:34> [main] source thread starting
<01/24/20@09:35:34> [main] opening client socket
<01/24/20@09:35:34> [source] listening for connection on port 6011
<01/24/20@09:35:34> [main] Client Stream thread [0] starting
<01/24/20@09:35:34> [main] client main thread starting
<01/24/20@09:37:29> [source] connected from 192.168.21.21  
<01/24/20@09:37:29> [source] icy-name: R-OK ; icy-genre: 
<01/24/20@09:37:29> [source] icy-pub:1 ; icy-br:128 ; icy-url: 
<01/24/20@09:37:29> [source] icy-irc:  ; icy-icq:  ; icy-aim: 
<01/24/20@09:37:30> [yp_add] yp.shoutcast.com gave error (nak)
<01/24/20@09:37:30> [yp_add] yp.shoutcast.com gave extended error (Please specify a genre for this station.)
*** snip snip ***

**Comment by ElvishArtisan** [comment]
I've just stood up an external instance of Shoutcast v1.9.8 for testing. Please check your private e-mail for details.

**Comment by workino** [comment]
Hello Fred,
modified some part and now is managing bot versions without problem.

Please look your email :)

Regards
Gabriele

**Comment by ElvishArtisan** [comment]
Looking good!

Please add a ChangeLog entry describing your changes, and we'll be good to go. [See the 'PULL REQUEST CHECKLIST' section of 'CODINGSTYLE' at the top of the source tree.]

**Comment by workino** [comment]
Hello Fred,
i didn't add the entry to changelog waiting your feedback.
 Let me know if you woul dlike to add also the entry for Username.

**Comment by ElvishArtisan** [comment]
The code works well with both Shoutcast v1.x and v2.x. Nice job!

A couple of questions, and a housekeeping item:

1) What is the relationship of this to the existing 'shoutcast1_pypad.py' plug-in. Is this intended to _replace_ that plug-in, or is it merely an addition? (Provided that the configuration is backwards-compatible, I see no reason that it couldn't replace the existing one).

2) What are the benefits of using a SID in the config?

3) If this is intended as a _new_ plug-in, then you will need to make the appropriate additions to the build system in ```apis/pypad/scripts/Makefile.am``` so that the script gets installed properly. (Just do a search for 'shoutcast1' in that file to see what needs to be done.

**Comment by workino** [comment]
Hello Fred,
sorry for delay. Yes i think the best will be to exchange the actual shoutcast to the new one how u propose. 
SID is used mainly in dnasv2 like username to specify the id of the stream. 
(look shoutcast.com is giving you SID to connect)

Regards
Gabriele

**Comment by ElvishArtisan** [comment]
Can we give the new Shoutcast script the same name ('pypad_shoutcast1.py') instead of a new name? Otherwise, this is going hand out a nasty surprise for anyone using the old one -- it will suddenly just not be there after the upgrade!

Otherwise, this is looking good.

**Pull request closed without merging**
