### PR TITLE
Increase minimum width of RDLibrary main window.

### PR DESCRIPTION
**Pull request by dklann**
In order to account for the "Use Realtime Filtering"
option for a host.

Signed-off-by: David Klann <dklann@linux.com>

### CODE REVIEW

**Comment by deltecent** [comment]
Good catch! But since this increases beyond the 1024 width, it may cause problems with people using that are still limited to that screen resolution. I propose that we rearrange the top display to fit within a 1024 display.

With your permission, I will submit that change today.

**Comment by dklann** [comment]
Ah, good point Patrick. I am spoiled with pretty much _only_ wide displays these days.

I was also going to propose moving the "Matching Carts" elements up by the "Filter" elements. I'll await Fred's final solution to check out your mods. Thanks!

**Comment by deltecent** [comment]
> I was also going to propose moving the "Matching Carts" elements up by the "Filter" elements. I'll await Fred's final solution to check out your mods. Thanks!

That's a good idea. Are you suggesting that the "Matching Carts" be placed between the Filter text field and the Search/Clear button, essentially shortening the Filter text field?

**Comment by ElvishArtisan** [comment]
There are still a surprising number of sites that are running Rivendell on 1024x768 displays. Thus, for now, we need to stay within that envelope; before we exceed it, I think we need to arrive at a consensus with the user community regarding what the new 'minimum size' ought to be.

**Comment by dklann** [comment]
Understood, and concur. With Patrick's and your changes to this, I withdraw the PR. It looks good to me, thanks!

**Pull request closed without merging**
