### PR TITLE
Add configuration option to convert event time from milliseconds to s…

### PR DESCRIPTION
**Pull request by deltecent**
…econds

### CODE REVIEW

**Comment by radiocafe** [comment]
Greetings to all!
Fred, are there chances to include these changes in future versions?
Also, this one : https://github.com/ElvishArtisan/rivendell/pull/197
Thanks!

**Comment by ElvishArtisan** [comment]
This is feeling a bit architecturally wonky. Rather than having %h/%H mean two different things, I think it'd make more sense to just define a new wildcard (%v/%V are available) to indicate "seconds".

**Comment by deltecent** [comment]
That works for me. I did this for another person that needed seconds. I’m not attached to any particular letter.

Is this something that you will change? I think my git is pretty messed up at the moment. I'm far from a git expert and I think I hosed a bunch of stuff up with the two branches. I’m planning to just start over with the next stable release.

What are your thoughts on the play/stop buttons in RDLibrary? We’ve found it extremely helpful and saves a lot of clicks when wanting go through music in the library looking for specific types of songs.

Thank you.

Patrick

**Comment by deltecent** [comment]
I see what you're saying.... That's a much better solution. I'll submit a new pull request.

**Comment by ElvishArtisan** [comment]
Implemented in adc747d35e91fb9ba16b04b7d462b1de153b765d.

**Comment by ElvishArtisan** [comment]
Whups! Just saw your comment. Didn't mean to trump you!

**Comment by deltecent** [comment]
Ah! Not a problem. At least now I know it was done right.

And thank you about the AUTHORS idea. Yes, I'd love to have my name in there for posterity.

Patrick Linstruth <patrick@deltecent.com>
   General bug fixes
   rlm_tunein

Patrick

**Comment by deltecent** [comment]
While I have you....

With my terrible understand of GIT, I lost my changes to purge the stack in rdmaint.

What I did was figure out how far back we need to go into the stack based on artist and title separation numbers. It then purges everything before and renumbers and index.

Does that sound like a reasonable way to deal with the ever-growing stack?

If so, how much time would I have to redo it and possibly get it into the 2.19.3 release?

Thank you,

Patrick


+void MainObject::PurgeStacks()
+{
+  QString sql;
+  RDSqlQuery *q;
+  RDSqlQuery *q1;
+  RDSqlQuery *q2;
+  int stackid;
+  int stacksize;
+  int artistsep=50000;
+  int titlesep=50000;
+
+  sql="select MAX(ARTISTSEP) from CLOCKS";
+  q=new RDSqlQuery(sql);
+  if(q->next()) {
+    artistsep=q->value(0).toInt();
+  }
+  delete q;
+
+  sql="select MAX(TITLE_SEP) from EVENTS";
+  q=new RDSqlQuery(sql);
+  if(q->next()) {
+    titlesep=q->value(0).toInt();
+  }
+  delete q;
+
+  stacksize=(artistsep<titlesep)?titlesep:artistsep;
+
+  sql="select NAME from SERVICES";
+  q=new RDSqlQuery(sql);
+  while(q->next()) {
+    QString tablename=q->value(0).toString()+"_STACK";
+    tablename.replace(" ","_");
+    sql=QString().sprintf("SELECT MAX(SCHED_STACK_ID) from %s",(const char*)tablename);
+    q1=new RDSqlQuery(sql);
+    if (q1->next())
+    { 
+      stackid=q1->value(0).toUInt();
+      if (stackid-stacksize > 0) {
+        sql=QString().sprintf("DELETE from `%s` where SCHED_STACK_ID <= %d", (const char*)tablename, stackid-stacksize);
+        q2=new RDSqlQuery(sql);
+        delete q2;
+      }
+
+      // Eventually, SCHED_STACK_ID is going to wrap back to 0.
+      // We may want to put something here to renumber the stack
+    }
+    delete q1;
+  }
+  delete q;
+}

int main(int argc,char *argv[])
{
diff --git a/utils/rdmaint/rdmaint.h b/utils/rdmaint/rdmaint.h
index 4cc8f3a..075a06b 100644
--- a/utils/rdmaint/rdmaint.h
+++ b/utils/rdmaint/rdmaint.h
@@ -44,6 +44,7 @@ class MainObject : public QObject
  void PurgeElr();
  void PurgeDropboxes();
  void PurgeGpioEvents();
+  void PurgeStacks();
  RDConfig *maint_config;
  bool maint_verbose;
  bool maint_system;

**Comment by ElvishArtisan** [comment]
On May 30, 2018, at 14:42, Deltec Enterprises <notifications@github.com> wrote:

> And thank you about the AUTHORS idea. Yes, I'd love to have my name in there for posterity.
> 
> Patrick Linstruth <patrick@deltecent.com <mailto:patrick@deltecent.com>>
> General bug fixes
> rlm_tunein

Done.

Also — for future PRs, feel free to include a ChangeLog entry with your contact info. Makes it easier to keep track of who did what…

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Pull request closed without merging**
