### PR TITLE
Add M4A import support using MP4V2 and libfaad.

### PR DESCRIPTION
**Pull request by smowton**
For details see http://caspian.paravelsystems.com/pipermail/rivendell-dev/2014-March/020438.html

### CODE REVIEW

**Comment by smowton** [comment]
Hi Fred, any progress on getting this one into the next release? Do let me know if there's anything I can do to help with that!

**Comment by ElvishArtisan** [comment]
Very clean job.  Thanks!

**Comment by ElvishArtisan** [comment]
On Mar 7, 2015, at 17:05 44, Chris Smowton <notifications@github.com> wrote:
> 
> Hi Fred, any progress on getting this one into the next release? Do let me know if there's anything I can do to help with that!

Hi Chris:

Just merged it.  Very nice, clean job!  It should appear in v2.11.0.  Thanks!

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by smowton** [comment]
Thanks! I've let the station techs know to move back to mainline as of then :)

**Pull request merged**
