### PR TITLE
Schedcartlist without arrays

### PR DESCRIPTION
**Pull request by albanpeignier**
We made some benchmarks on rdlogmanager log generation, to especially understand the reasons of the high CPU usage.

In fact ... the slowness is due to a bad choise of data structure in SchedCardList. It uses arrays and the item removal is very expensive, ... but it's the first usage 

This patch is refactoring SchedCardList by using a linked list of SchedCard objects.

The logic is the same, but the generation time has changed :

**Before :**

 ```
rdlogmanager -g -s Grille_A -d 1
441.38s user 0.31s system 94% cpu 7:48.03 total
 ```

**After :**

 ```
rdlogmanager -g -s Grille_A -d 1
10.08s user 0.22s system 29% cpu 34.661 total
 ```

It's 13x faster 

The patch contains 4 other commits to improve SQL queries performed by generateLog (which saves few seconds).

We tested this patch on several customer databases.

### CODE REVIEW

**Comment by albanpeignier** [comment]
Any chance for v2.11.0 ? :-)

**Comment by ElvishArtisan** [comment]
On Mar 10, 2015, at 04:39 35, Alban Peignier <notifications@github.com> wrote:

> Any chance for v2.11.0 ? :-)

I’d say, chances are excellent for both!  :)

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by albanpeignier** [comment]
You can test this pull request by using the debian packages we've built. They include Rivendell 2.10.3 and the patch proposed by this pull request : 

```
wget http://download.tryphon.eu/debian/wheezy/librivendell_2.10.3-1+pr44_amd64.deb \
  http://download.tryphon.eu/debian/wheezy/rivendell_2.10.3-1+pr44_amd64.deb \
  http://download.tryphon.eu/debian/wheezy/rivendell-server_2.10.3-1+pr44_amd64.deb

sudo dpkg -i librivendell_2.10.3-1+pr44_amd64.deb rivendell_2.10.3-1+pr44_amd64.deb rivendell-server_2.10.3-1+pr44_amd64.deb
```

caed (especially with large sound cards) should use half the processor.

Packages are available for wheezy amd64 but we can build any debian/ubuntu platform.

**Comment by ElvishArtisan** [comment]
Merged to master.  Thanks!

**Pull request merged**
