### PR TITLE
(Master New Feature) 'FG' Macro

### PR DESCRIPTION
**Pull request by deltecent**
New 'FG' (Fade and Go) macro fades the currently playing log entry and starts the next. Good for playing news,weather,etc over music bed and stopping the bed in sync with the voice over.

The log would look like the following:

Weather Music Bed - Segue
Weather Voice - Segue
FG Macro - Segue

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
This is not working in quite the way that it is described in the Ops Guide. My test procedure:

1. Load up a log in rdairplay(1)'s Main Log. (All events in the log have SEGUE transition).

2. Ensure that the mode is AUTOMATIC.

3. Start playing the first cart in the log.

4. Fire up rmlsend(1) and send the following command to LOCALHOST:

```FG 1 2000!```

The playing event fades down over a 2 second period and then stops, but the following event never starts --i.e. the entire log stops down. According to the Ops Guide, the next event should start.

**Comment by deltecent** [comment]
Interesting... I have not tested since I pushed this up. I could have something to do with the next cart having a PLAY transition rather than segue. I will do more testing.

**Comment by ElvishArtisan** [comment]
I'm thinking that the proper behavior should be "honor the following transition type" rather than 'start the following event'. Then we'd have a graceful way to fade and then STOP (useful for joining live or satellite programming).

**Comment by deltecent** [comment]
I agree. Let's put this on hold until I can do more testing.

**Comment by ElvishArtisan** [comment]
Or even provide an optional additional argument where a transition type could be given that would *override* whatever the following transition would be. See for example the 'Insert cart' ['PX'] RML.

**Comment by deltecent** [comment]
I am going to revisit this macro...

**Pull request closed without merging**
