### PR TITLE
(Master Regression) Fixed regression with RDTransportButton taking focus

### PR DESCRIPTION
**Pull request by deltecent**

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
This does not fix the problem here. Steps to reproduce:
1) Open an Event in rdlogmanager(1).
2) Select a line in the 'PRE-IMPORT CARTS' list.
3) Shift focus to a different window on the desktop. The line in the 'PRE-IMPORT CARTS' list gets de-selected.

**Comment by deltecent** [comment]
Interesting... I didn't check changing windows. The buttons didn't work at all without changing windows, which I fixed. I'll look at how to fix changing windows. I wonder if this is broke is other apps?

**Comment by deltecent** [comment]
The loss of selection is done on purpose. There's an ```ImportListView::focusOutEvent``` defined which deselects any selections should the object lose focus. I think we should get rid of that.

**Comment by ElvishArtisan** [comment]
Good catch!

Merged to 'master'. Thank you!

**Pull request merged**
