### PR TITLE
Added '--scheduler-code=' switch to rdexport(1).

### PR DESCRIPTION
**Pull request by deltecent**

### CODE REVIEW

**Comment by deltecent** [comment]
> export carts that match both criteria --i.e. export carts whose number fall in the range 10001:10009 and that have selector code 'FOO'.

That was my intention. I will see why that isn't working and update.

**Comment by deltecent** [comment]
When I run it, it does both. It runs the scheduler codes and then the carts. The order of processing is:
Titles
Groups
Scheduler Codes
Cart Number

What I did discover is `export_verbose` was not initialized to false, so sometimes I'd get verbose output and other times I wouldn't. I fixed that.

Would you run again and make sure it isn't exporting scheduler codes and then carts?

**Comment by ElvishArtisan** [comment]
It still appears to be ignoring the constraint from the ```--carts``` switch. I'm using the following invocation:

```rdexport --verbose --carts=10001:10009 --scheduler-code=FRED .```

Same behavior both with and without the ```--verbose``` switch.

**Comment by deltecent** [comment]
Unless I'm misunderstanding something, I don't believe `--carts` is a constraint on the other switches. The `--carts` switch works all by itself, export carts x through y. Now whether or not it "should be" a constraint is another question.

`rdexport --verbose --carts=10001:10009 --scheduler-code=FRED .`

This will export all carts with a scheduler code "FRED" and will also export carts 10001-10009.

```
  //
  // Process Titles
  //
  for(unsigned i=0;i<export_titles.size();i++) {
    Verbose("Processing title \""+export_titles[i]+"\"...");
    ExportTitle(export_titles[i]);
  }

  //
  // Process Groups
  //
  for(unsigned i=0;i<export_groups.size();i++) {
    Verbose("Processing group \""+export_groups[i]+"\"...");
    ExportGroup(export_groups[i]);
  }

  //
  // Process Scheduler Codes
  //
  for(unsigned i=0;i<export_schedcodes.size();i++) {
    Verbose("Processing scheduler code \""+export_schedcodes[i]+"\"...");
    ExportSchedCode(export_schedcodes[i]);
  }

  //
  // Process Cart Ranges
  //
  for(unsigned i=0;i<export_start_carts.size();i++) {
    for(unsigned j=export_start_carts[i];j<=export_end_carts[i];j++) {
      ExportCart(j);
    }
  }
```

**Comment by ElvishArtisan** [comment]
Point taken; multiple ```carts``` switch invocation _are_ OR'd together, as are ```--group``` values. So the current behavior is more consistent.

**Comment by ElvishArtisan** [comment]
Merged to 'master'. Thank you!

**Pull request merged**
