### PR TITLE
Refactors RDCddbLookup to use QTcpSocket instead of Q3Socket

### PR DESCRIPTION
**Pull request by deltecent**
This should fix issue #473. Needs to be tested by @validmirror.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
I'm getting inconsistent results here. I'm testing with two discs:
Disc1 = 'Walt Disney Pictures Presents The Little Mermaid' [DiscID: 1b0a2514].
Disc2 = 'Walt Disney Pictures Presents Beauty and the Beast' [DiscID: c90bc40f].

Both discs display data from FreeDB with Rivendell v2.19. However, with v3.0 and this PR, only Disc 1 does so.  Disc2 does not. This is with Paranoia Level set to 'Normal' and ISRC reading disabled (both discs date from the late 80s/early 90s and so have no encoded ISRC data).

Here's what I get when running rdlibrary(1) with the ```--profile-ripping``` switch:

Disc1:
```
13:33:23.155 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:33:23.189 | RDCddbLookup::recevied from server: "201 mirror1.freedb.org CDDBP server v1.5.2PL0 ready at Fri Aug 30 19:33:23 2019
"
13:33:23.189 | RDCddbLookup::sent to server: "cddb hello rdlibrary elastigirl.rfa.org rivendell 3.0.3"
13:33:23.256 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:33:23.258 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:33:23.293 | RDCddbLookup::recevied from server: "200 Hello and welcome rdlibrary@elastigirl.rfa.org running rivendell 3.0.3.
"
13:33:23.293 | RDCddbLookup::sent to server: "cddb query 1b0a2514 20 150 7742 14207 16485 19537 34220 48880 59240 81137 88340 100615 103460 110580 125620 134250 140657 147217 153452 163897 180645 2599"
13:33:23.359 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:33:23.360 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:33:23.398 | RDCddbLookup::recevied from server: "200 soundtrack 1b0a2514 Howard Ashman & Alan Menken / The Little Mermaid
"
13:33:23.398 | RDCddbLookup::sent to server: "cddb read soundtrack 1b0a2514
"
13:33:23.462 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:33:23.463 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:33:23.504 | RDCddbLookup::recevied from server: "210 soundtrack 1b0a2514 CD database entry follows (until terminating `.')
"
13:33:23.504 | RDCddbLookup::recevied from server: "# xmcd
"
13:33:23.504 | RDCddbLookup::recevied from server: "#
"
13:33:23.504 | RDCddbLookup::recevied from server: "# Track frame offsets:
"
13:33:23.504 | RDCddbLookup::recevied from server: "#	150
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	7742
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	14207
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	16485
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	19537
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	34220
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	48880
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	59240
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	81137
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	88340
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	100615
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	103460
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	110580
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	125620
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	134250
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	140657
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	147217
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	153452
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	163897
"
13:33:23.505 | RDCddbLookup::recevied from server: "#	180645
"
13:33:23.505 | RDCddbLookup::recevied from server: "#
"
13:33:23.505 | RDCddbLookup::recevied from server: "# Disc length: 2599 seconds
"
13:33:23.505 | RDCddbLookup::recevied from server: "#
"
13:33:23.505 | RDCddbLookup::recevied from server: "# Revision: 12
"
13:33:23.505 | RDCddbLookup::recevied from server: "# Processed by: cddbd v1.5.2PL0 Copyright (c) Steve Scherf et al.
"
13:33:23.505 | RDCddbLookup::recevied from server: "# Submitted via: dBpowerAMP V4.0
"
13:33:23.505 | RDCddbLookup::recevied from server: "#
"
13:33:23.505 | RDCddbLookup::recevied from server: "DISCID=1b0a2514
"
13:33:23.505 | RDCddbLookup::recevied from server: "DTITLE=Howard Ashman & Alan Menken / The Little Mermaid
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE0=Fathoms Below
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE1=Main Titles
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE2=Fanfare
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE3=Daughters Of Triton
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE4=Part Of Your World
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE5=Under The Sea
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE6=Part Of Your World (reprise)
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE7=Poor Unfortunate Souls
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE8=Les Poissons
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE9=Kiss The Girl
"
13:33:23.505 | RDCddbLookup::recevied from server: "TTITLE10=Fireworks
"
13:33:23.506 | RDCddbLookup::recevied from server: "TTITLE11=Jig
"
13:33:23.506 | RDCddbLookup::recevied from server: "TTITLE12=The Storm
"
13:33:23.506 | RDCddbLookup::recevied from server: "TTITLE13=Destruction Of The Grotto
"
13:33:23.506 | RDCddbLookup::recevied from server: "TTITLE14=Flotsam And Jetsam
"
13:33:23.506 | RDCddbLookup::recevied from server: "TTITLE15=Tour Of The Kingdom
"
13:33:23.506 | RDCddbLookup::recevied from server: "TTITLE16=Bedtime
"
13:33:23.506 | RDCddbLookup::recevied from server: "TTITLE17=Wedding Announcement
"
13:33:23.506 | RDCddbLookup::recevied from server: "TTITLE18=Eric To The Rescue
"
13:33:23.564 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:33:23.566 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:33:23.647 | RDCddbLookup::recevied from server: "TTITLE19=Happy Ending
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTD=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT0=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT1=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT2=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT3=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT4=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT5=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT6=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT7=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT8=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT9=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT10=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT11=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT12=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT13=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT14=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT15=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT16=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT17=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT18=
"
13:33:23.647 | RDCddbLookup::recevied from server: "EXTT19=
"
13:33:23.647 | RDCddbLookup::recevied from server: "PLAYORDER=
"
13:33:23.647 | RDCddbLookup::recevied from server: ".
"
13:33:23.647 | RDCddbLookup::sent to server: "quit"
13:33:23.657 | RDCddbLookup::CDDB lookup finished
1
```
Disc2:
```13:37:34.055 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:37:34.060 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:37:34.162 | RDCdPlayer::ReadToc() started
13:37:34.242 | RDCdPlayer::ReadToc() finished
13:37:34.242 | RDCdPlayer::emitting mediaChanged()
13:37:34.243 | RDCddbLookup::starting CD-TEXT lookup
13:37:35.314 | RDCddbLookup::CD-TEXT lookup failure
13:37:35.314 | RDCddbLookup::starting CDDB lookup
13:37:35.314 | RDCdPlayer::mediaChanged() emitted
13:37:35.314 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:37:35.322 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:37:35.423 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:37:35.424 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:37:35.529 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:37:35.531 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:37:35.562 | RDCddbLookup::recevied from server: "201 mirror1.freedb.org CDDBP server v1.5.2PL0 ready at Fri Aug 30 19:37:35 2019
"
13:37:35.562 | RDCddbLookup::sent to server: "cddb hello rdlibrary elastigirl.rfa.org rivendell 3.0.3"
13:37:35.632 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:37:35.634 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:37:35.669 | RDCddbLookup::recevied from server: "200 Hello and welcome rdlibrary@elastigirl.rfa.org running rivendell 3.0.3.
"
13:37:35.669 | RDCddbLookup::sent to server: "cddb query c90bc40f 15 182 11190 34415 39297 55812 65120 81992 92435 108237 120737 129607 146285 156962 181677 207772 3014"
13:37:35.735 | RDCdPlayer::calling ioctl(CDROMSUBCHNL)
13:37:35.737 | RDCdPlayer::ioctl(CDROMSUBCHNL) success
13:37:35.775 | RDCddbLookup::recevied from server: "200 soundtrack c90bc40f Various / Beauty And The Beast
"
13:37:35.775 | RDCddbLookup::sent to server: "quit"
13:37:35.775 | RDCddbLookup::CDDB lookup finished
13:37:35.775 | RDCddbLookup::sent to server: "cddb read soundtrack 00000000
"
```
What is particularly interesting here is that **both** discs return a match from FreeDB, but with Disc2 we hangup immediately after getting the match, rather than requesting the track list.

**Comment by deltecent** [comment]
What you're seeing with disc 2 is what I was seeing all the time with my Duran Duran / Rio CD. After switching to QTcpSocket, that CD worked fine every time.

I'll test with more CDs and see if I can get one to fail.

Patrick

**Comment by deltecent** [comment]
Give this a try. Needed to change "toInt()" to "toUInt()" for the disc id.

**Comment by ElvishArtisan** [comment]
That makes sense, given that ```INT``` is 32 bits on x86_64. Setting the most significant bit thus makes the value be intepreted as twos-complement --i.e. a *negative* value. Since a DiscID is defined to be an '8-digit hexadecimal (base-16) number' (see http://ftp.freedb.org/pub/freedb/misc/freedb_howto1.07.zip), ```UNSIGNED INT``` should suffice for all modern architectures.

**Comment by ElvishArtisan** [comment]
Looking good now with disk IDs >=0x80000000.

Merged to 'master'. Thank you!

**Pull request merged**
