### PR TITLE
(Master OpsGuide) Added RDLibrary play buttons to opsguide

### PR DESCRIPTION
**Pull request by deltecent**
May also need to update cart list image.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
Should I hold off merging this until the screenshot has been updated?

**Comment by deltecent** [comment]
I’ve never done a screenshot on CentOS. I can send one up and see what you think.

Patrick

**Comment by ElvishArtisan** [comment]
Just install the 'xfce4-screenshooter' package. You invoke it by a command of the same name. There are various keybindings for it built-in to the xfce4 desktop, but I seldom bother with them.

**Comment by ElvishArtisan** [comment]
Merged to 'master'. Thank you!

**Pull request merged**
