### PR TITLE
Fix undefined symbol when using ProcessNullUpdates in configuration file

### PR DESCRIPTION
**Pull request by fpeyraud**
Hello
When using pypad_udp.py, the pypad instance crashed complaining about undefined pypad object. This pull requests fixes this issue
Regards
Florent

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
Hmm. That doesn't look right. ```TYPE_NOW``` and ```TYPE_NEXT``` are declared to be part of the ```pypad``` namespace. It works fine here on my setup (source build from Git on CentOS 7 with Python 3.6). On what environment are you seeing this error?

**Comment by fpeyraud** [comment]
Hello
I'm running rivendell 4.0.0beta3int3 on Ubuntu 22.04 (python 3.10). The issue (and fix) is duplicated on 2 distinct but similar systems. The configuration file `pypad_udp.exemplar` is as follows :
```
; This is the sample configuration for the 'pypad_udp.py' PyPAD script for 
; Rivendell, which can be used to output Now & Next data to one or more
; remote UDP ports.

; Section Header
;
; One section per remote UDP port is configured, starting with 'Udp1' and 
; working up consecutively
[Udp1]

; IP Address
;
; The IP address of the remote UDP port, in dotted-quad notation.
IpAddress=127.0.0.1

; UDP Port
;
; The UDP port number of the remote UDP port, in the range 0 - 65,535.
UdpPort=12345

; Format String.  The string to be output each time RDAirPlay changes
; play state, including any wildcards as placeholders for metadata values.
;
; The list of available wildcards can be found in the 'metadata_wildcards.txt'
; file in the Rivendell documentation directory.
;
FormatString=NOW: %d(ddd MMM d hh:mm:ss yyyy): %t - %a\nNEXT: %D(ddd MMM d hh:mm:ss yyyy): %T - %A\n

; Encoding.  Defines the set of escapes to be applied to the PAD fields.
; The following options are available:
;
;  0 - Perform no character escaping.
;  1 - "XML" escaping: Escape reserved characters as per XML-v1.0
;  2 - "Web" escaping: Escape reserved characters as per RFC 2396 Section 2.4
Encoding=0

; Null Update Handling.  Defines how 'null' updates --i.e. those with a cart
; number of '0' -- should be handled.
;
;  0 - Process all updates regardless of cart values.
;  1 - Process update only if the 'now' cart is not null.
;  2 - Process update only if the 'next' cart is not null.
;  3 - Process update only if both the 'now' and 'next' carts are not null.
ProcessNullUpdates=1

; Log Selection
;
; Set the status for each log to 'Yes', 'No' or 'Onair' to indicate whether
; state changes on that log should be output on this udp port.  If set
; to 'Onair', then output will be generated only if RDAirPlays OnAir flag
; is active.
MasterLog=Yes
Aux1Log=Yes
Aux2Log=Yes
VLog101=No
VLog102=No
VLog103=No
VLog104=No
VLog105=No
VLog106=No
VLog107=No
VLog108=No
VLog109=No
VLog110=No
VLog111=No
VLog112=No
VLog113=No
VLog114=No
VLog115=No
VLog116=No
VLog117=No
VLog118=No
VLog119=No
VLog120=No


[NowGroups]
; Group Selection
;
; Filter updates according to the Group membership of the 'now' playing
; event. If no groups are listed here and in the [NextGroups] section,
; then ALL updates will be forwarded
; without regard to Group.
; Group1=MUSIC
; Group2=LEGAL
; [...] ; Additional groups can be added...

[NextGroups]
; Group Selection
;
; Filter updates according to the Group membership of the 'next' playing
; event. If no groups are listed here, If no groups are listed here and in
; the [NowGroups] section,then ALL updates will be forwarded
; without regard to Group.
; Group1=MUSIC
; Group2=LEGAL
; [...] ; Additional groups can be added...
```

**Comment by ElvishArtisan** [comment]
Thanks. Spinning up Ubuntu 22.04 here to test. Stand by...

**Comment by fpeyraud** [comment]
In order to make the issue pop up, I had to set the `ProcessNullUpdates` to something different from `0`, otherwise the code does not enter the `if` branch in which the patch does the job

**Comment by ElvishArtisan** [comment]
Ah, I see. Your change is in the module code, not the plug-ins. That makes sense.

Please add a ```ChangeLog``` entry, and I will merge this.

**Comment by fpeyraud** [comment]
Hi,
Entries added. Thanks ;)

**Comment by ElvishArtisan** [comment]
Merged to 'qt5'. Thank you!

**Pull request merged**
