### PR TITLE
(Master Bug Fix) Add dropbox logging to rdimport

### PR DESCRIPTION
**Pull request by deltecent**

### CODE REVIEW

**Comment by deltecent** [comment]
Syslog?

**Comment by ElvishArtisan** [comment]
See 'man 2 syslog'

This is how one writes to the 'system' logging facility. Using this facility has many advantages over merely writing to a file, as it automatically supports things like log rotation, logging to different files depending on facility and priority of message, logging to remote systems, etc.

**Comment by ElvishArtisan** [comment]
Correction: see 'man 3 syslog'.

**Comment by deltecent** [comment]
I will resubmit this PR with syslog rather than fprintf. Thank you.

**Comment by deltecent** [comment]
Would it be a good a idea to keep the file logging for backwards compatibility and add syslog? The file logging allows people to specify a separate log file for each dropbox, which can be done with syslog, but requires more knowledge of managing syslog. But then the question becomes do we leave the file path information in RDAdmin or have a select box for File or Syslog logging or both?

**Comment by ElvishArtisan** [comment]
On Oct 3, 2018, at 10:03, Deltec Enterprises <notifications@github.com> wrote:

> Would it be a good a idea to keep the file logging for backwards compatibility and add syslog? The file logging allows people to specify a separate log file for each dropbox, which can be done with syslog, but requires more knowledge of managing syslog. But then the question becomes do we leave the file path information in RDAdmin or have a select box for File or Syslog logging or both?

We could go either way. There are parameters in rd.conf(5) already that the rest of Rivendell currently uses to configure logging via syslog vs. a simple file (see the ‘[Logs]’ section). However, rdimport(1) has never used those, so I’m thinking a better approach would be to make it a command-line option (with corresponding options in the Dropbox config dialog in rdadmin(1)).

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Pull request closed without merging**
