### PR TITLE
(Master) Move 'CART.SCHED_CODES' field to 'CART_SCHED_CODES' table.

### PR DESCRIPTION
**Pull request by deltecent**
This was a fairly intrusive change. Some help with additional testing is necessary.

I also think it does slow down log generation. There's probably an optimization out there.

### CODE REVIEW

**Comment by deltecent** [comment]
Log generation scheduler optimized.

**Comment by ElvishArtisan** [comment]
I will test as soon as I can (my system here is currently in pieces while integrating TagLib).

**Comment by ElvishArtisan** [comment]
One suggestion: in 'updateschema.cpp', I see that you're using ```RDCart:setSchedCodes()``` to write to the new table. This is problematic because it assumes that that method will always conform to schema 299. However, suppose the schema for storing schedule codes changes again in future? That would break this schema update!

Good practice is to avoid relying on the convenience library classes when doing schema transformations (in *either* direction). Using anything fancier than ```RDSqlQuery``` is probably asking for trouble.

**Comment by deltecent** [comment]
I'll get that changed tonight.

**Comment by ElvishArtisan** [comment]
Merged to 'master'. Thank you!

**Pull request merged**
