### PR TITLE
(Master) Implement "Use Event Length for PAD Updates" Macro Cart Option

### PR DESCRIPTION
**Pull request by deltecent**
The ```CART.USE_EVENT_LENGTH``` field is set in ```RDLibrary``` when editing a macro cart but the option isn't used anywhere.

I updated ```RDLogPlay::SendNowNext()``` to use the event lengths in determining PAD data if ```useEventLength()``` of a macro cart is true, otherwise, send the macro's PAD data regardless of event lengths.

I also removed some extraneous ```>``` characters in ```rml.xml``` while editing the documentation.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
This is not how that feature is supposed to work. The 'event' referred to in the Edit Cart dialog is (confusingly) an _rdlogmanager(1)_ event, not a log one. The use case for this feature is live inserts (such as satellite programming), where you want to post a PAD update for a piece of externally sourced programming, during which the rdairplay(1) log will be stopped down. This allows the correct event length to be sent with the update (critical for certain consumers of PAD).

I'd certainly be open for a change of the wording on the checkbox to make this less confusing. The challenge is making it fit in the available space.

And, I see upon testing this here, that I managed to break this feature when making the PyPAD changes. &lt;sigh&gt;...

**Comment by deltecent** [comment]
Ok, then I'd like to come up with a way to have a macro event, which generally has a length of 0, be able to have it's PAD data sent unless you think that's a bad idea.

**Comment by ElvishArtisan** [comment]
deltacent said:
> Ok, then I'd like to come up with a way to have a macro event, which generally has a length of 0, be 
> able to have it's PAD data sent unless you think that's a bad idea.

Just play it in a log, and ensure that its parent group is enabled to send Now & Next.

**Comment by ElvishArtisan** [comment]
Or is this a reference to #356?

**Comment by deltecent** [comment]
> Just play it in a log, and ensure that its parent group is enabled to send Now & Next.
I can't make that work unless the event before the macro doesn't have a segue. If the event before the macro has a segue, that it is always considered to be the "now" event as now/next is based on the longest event, and unless there's a SP in the macro, they have no length.

If the log is:

Cart 1: Segue
Macro
Cart 2: Segue

The now PAD data sent will be:

Cart 1
Cart 1
Cart 2

**Comment by ElvishArtisan** [comment]
I'm unable to reproduce those results here. How are you viewing the updates? Have you tried doing a telnet to port 34289 on the Rivendell system and looking at the raw JSON as it's emitted?

**Comment by ElvishArtisan** [comment]
Ok, I think I finally see what's happening here. It's a corner case; if the length of the macro cart is shorter than the length of the segue overlap [SEGUE_END-SEGUE_START], then the PAD from the macro cart never gets emitted. The mere presence of an 'SP' RML does not guarentee that the suppression will be prevented. That effect does _not_ happen if the 'short' event is an audio cart, so there looks to be more to it than mere relative lengths.

Digging into the code right now...

**Comment by deltecent** [comment]
That's it exactly! And 'SP' is a bad idea because the entire log stops for the duration.

I scattered 'fprintf(stderr,...)" all over the place to see the updates being sent and what was happening internally.

**Comment by ElvishArtisan** [comment]
For the moment, I've just posted a change to 'master' [4cadda9] that changes the PAD dispatching algorithm to use the 'most recently started' rather than the 'longest running' strategy, which seems to fix the immediate problem at hand. The implementation of the old strategy is still there too, commented out ['lib/rdlogplay.cpp', lines 2879-2890].

Now, is there a reasonable heuristic we could use to determine which strategy would be best to apply in any given situation?

**Comment by deltecent** [comment]
For my purposes, I like the 'longest running' strategy unless it's a macro, in which case use 'most recently started'. Since a macro typically doesn't have any length, the 'longest running' will be dispatched nearly instantaneously after the macro. I think in most cases, people wouldn't be sending now&next with macros, but if they are, that probably means they want to see the PAD data.

**Comment by ElvishArtisan** [comment]
'Kay, I've just updated this to use a 'hybrid' strategy --i.e. use longest-running, _except_ when the most recently started event is a macro cart that is also enabled for Now & Next, in which case the macro cart's PAD gets used.

**Pull request closed without merging**
