### PR TITLE
Four log outputs

### PR DESCRIPTION
**Pull request by k2fc**
This increases the number of Main Log Output Channels in RDAirPlay from two to four. 

It hasn't been tested with GPIO yet.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
What exactly is the rationale for this? How are the additional outputs used?

**Comment by k2fc** [comment]
When running in manual mode, it can be difficult to perform a segue with only two faders.  If running a music show, the log would typically have two songs separated by a jingle or piece of imaging.  Segueing from one song to the next would end up with three things playing simultaneously.  If you are running this show manually, you would want each of these elements on a separate fader.  

Also, you may have something like a traffic report, which consists of two carts: the voice and the music bed.  These would already be taking up two faders.  Once this ends, it would require a third fader if you wanted to segue out of that.

**Comment by k2fc** [comment]
It goes in "round robin" across the four outputs.  If 1 is playing, the
next will play from 2, then 3, then 4, then 1.  This is the behavior of
other automation systems with multiple outputs running in Automatic mode.

**Comment by ElvishArtisan** [comment]
I'm wondering if we need a bit more configurability there.  Back in the day of hard-wired analog consoles, that made sense, but in a modern AoIP plant it's common to remap your faders for different dayparts.  It seems wasteful to have to dedicate 4 faders during dayparts when the automation is in Automatic.

This might be a good discussion to raise on Rivendell-dev.

**Comment by k2fc** [comment]
There's no need with this change to dedicate those faders if you don't want
to.  Just like the second log output can currently be set to None if you
want to run the main log out of one fader, the same can be done; just set
the other outputs to None.

I agree that some more configurability would be good here (something
similar to RDCartSlots' n number of outputs might be a place to start) but
that would require some more involved reworking of RDAirPlay.



On Nov 7, 2017 12:00, "Fred Gleason" <notifications@github.com> wrote:

I'm wondering if we need a bit more configurability there. Back in the day
of hard-wired analog consoles, that made sense, but in a modern AoIP plant
it's common to remap your faders for different dayparts. It seems wasteful
to have to dedicate 4 faders during dayparts when the automation is in
Automatic.

This might be a good discussion to raise on Rivendell-dev.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ElvishArtisan/rivendell/pull/185#issuecomment-342549924>,
or mute the thread

**Pull request closed without merging**
