### PR TITLE
(Master Feature) Move rdlogmanager(1) scheduler artist separation from clock to event.

### PR DESCRIPTION
**Pull request by deltecent**
This PR moves the artist separation setting for Rivendell's scheduler from `Rivendell.CLOCKS` to `Rivendell.EVENTS` This allows each event to specify its own artist separation the same as title separation. It is also now possible to set artist and/or title separation to "None".

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
Is there a way that we could populate the new per-event separation field with some sane default value (perhaps derived from previous clock-based values)?

Do we need to keep the old clock-based values around?  If so, I think we need to clearly indicate in the UI that these values are 'informational only' (perhaps grey-out the spinbox)?

**Comment by deltecent** [comment]
> Is there a way that we could populate the new per-event separation field with some sane default value (perhaps derived from previous clock-based values)?
> 
> Do we need to keep the old clock-based values around? If so, I think we need to clearly indicate in the UI that these values are 'informational only' (perhaps grey-out the spinbox)?

I think I did both of those, unless I pushed the wrong stuff, again.

rddbconfig runs through the clocks, finds the largest number, and uses that for the events.

The spinbox is also be greyed out with a note that says the setting is deprecated and moved to the events. I chose to leave the setting there so people go back and see what they had them set to. The idea was to remove it in 3.1.

**Comment by ElvishArtisan** [comment]
Ah - I see it. Perfect.

One last detail: the schema map in ```utils/rddbmgr/schemamap.cpp``` is still showing 306 as the canonical schema for 3.0.x. Bump that to 307 and we should be good to go.

**Comment by ElvishArtisan** [comment]
Merged to 'master'. Thank you!

**Pull request merged**
