### PR TITLE
Corrects Delete Event dialog with proper event identifier

### PR DESCRIPTION
**Pull request by deltecent**

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
I find this change very confusing.  Why do we need all of the extra information in the confirmation dialog?

**Comment by deltecent** [comment]
There is confirmation dialog to ensure that the event being deleted from a clock is the one you really want. The current version of Rivendell displays, I believe, the length of the event, which makes the confirmation dialog ambiguous.

While I don't know if you need all the information (start time, end time, and description) in the dialog, the dialog should contain something that clearly identifies the actually event that is going to be deleted.

**Comment by ElvishArtisan** [comment]
On Mar 15, 2017, at 17:43, deltecent <notifications@github.com> wrote:

> While I don't know if you need all the information (start time, end time, and description) in the dialog, the dialog should contain something that clearly identifies the actually event that is going to be deleted.

Makes sense.  So how about we use just start time (MM:SS) and the Event Name?  That would permit unambiguous identification without overwhelming the user with unnecessary clutter.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by deltecent** [comment]
That works for me.

Does that mean you incorporate this change and you make your suggested change or do I have to get better at Git and figure out how to undo and/or change a commit and pull request?

**Pull request closed without merging**
