### PR TITLE
(3.0.0rc02 Feature) Added rdmetadata(8) utility and notification_test harness.

### PR DESCRIPTION
**Pull request by deltecent**
Provides the ability to set cart metadata from the command line.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
Nice idea. I like it!

A couple of observations:
1) It appears that a multicast notification is not being generated after applying the change(s). Thus, other modules are not updating their views to reflect the change.

2) I notice that you've made this to require 'root' privileges. Would it be possible to have it run under an ordinary user, using the standard Rivendell privileges system to verify that the current Rivendell user has the appropriate ```RDUser::modifyCarts()``` permission? [See the ```MainObject:::userData()``` method in rdimport(1) for an example of how this can done in a CLI context].

**Comment by deltecent** [comment]
Both are great suggestions. I thought I had the notification in there, but apparently didn't test it.

**Comment by deltecent** [comment]
It should be good to go now. I also added a simple ```notification_test``` harness.

It took me a while to figure out why the notifications weren't making it. I found the answer in ```rdimport```:
```
  //
  // Allow the notification to be processed
  //
  qApp->processEvents();
```

**Comment by ElvishArtisan** [comment]
Looks good. Thank you!

I have one additional request: could we please change the default behavior back to writing nothing to stdout in the event of success, with a --verbose flag to enable the status reporting? This would be in line with [The Rule of Silence](http://www.catb.org/~esr/writings/taoup/html/ch01s06.html#id2878450) as well as consistent with the behavior of all other Rivendell CLI programs.

**Comment by ElvishArtisan** [comment]
Merged to 'master'. Thank you!

**Pull request merged**
