### PR TITLE
MusicMaster Nexus Integration (Alpha)

### PR DESCRIPTION
**Pull request by deltecent**
This PR adds the current development state of MusicMaster Nexus integration to Rivendell 3.0.2.

The development cycle of this integration has reached the point where it will be beneficial for users of MusicMaster to begin testing this integration and providing feedback of bugs and changes/recommendations.

Although I tried to leave core Rivendell components alone, the following changes were necessary:

Adds ```RDGroupList::loadGroup``` method.
Adds ```RDStation::list``` method.
Adds ```CART.MINUMUM_TALK_LENGTH``` and ```CART.MAXIMUM_CART_LENGTH``` rows.
Modifies RDCart class to read/write/update new talk lengths.
Modifies rdlibrary(1) to use the new talk length cart rows.
Adds a timestamp to RDNotification.
Adds an optional QVariant argument to RDNotification.
Adds new notification types and actions to RDNotification.
Adds Start and Stop Playout notifications to RDLogPlay class.
Modifies rdservice to launch rdnexusd if enabled in rdadmin.
Adds a standardized "MusicMaster Nexus" import template to rdadmin.
Modifies rdadmin to show import template offset values.
Adds a "MusicMaster Nexus" button to rdadmin.
Modifies rddbmgr to update/revert the database schema to/from 310.

All other additions are unique to the Nexus integration and should not impact other areas of Rivendell:

Adds RDHttpServer class.
Adds RDNexus class.
Adds rdnexusd daemon
Adds 'NEXUS_FIELDS','NEXUS_QUEUE','NEXUS_SERVER', and 'NEXUS_STATIONS' tables.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
Looks very nice! I'm looking forward to giving this a spin.

In light of the 'Alpha' tag, would it make more sense to roll this this into a separate release that is tagged as being specifically for purposes of Nexus testing, rather than merging it to 'master'?

**Comment by deltecent** [comment]
I think that would be a good idea. I wasn’t sure what the options were so I’d leave it to your best judgement.

Patrick

**Comment by ElvishArtisan** [comment]
'Kay, I will package it up with a 'nexus' tag ['v3.0.2nexus0', 'v3.0.2nexus1', etc].

Please write up a blurb (paragraph or two) that I can include in the release announcement explaining what this is, how to report bugs, etc.

**Comment by ElvishArtisan** [comment]
Does this PR address #469?

**Comment by deltecent** [comment]
It should for the CUTS query that was reported, but I have not tested it.

**Comment by deltecent** [comment]
This PR is now outdated.

**Pull request closed without merging**
