### PR TITLE
Add pypad_tunein.py and pypad_icecast2.py

### PR DESCRIPTION
**Pull request by deltecent**
If this is acceptable, I'll start on some of the others.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
Any chance we could split these into two separate PRs? The rdairplay(1) fix really belongs in 'master', not the 'rlm2' development branch.

**Comment by ElvishArtisan** [comment]
Daemonize? You don't find this a tad non-orthogonal, especially seeing as we will be adding a script management system?

**Comment by ElvishArtisan** [comment]
How much work would it be to make this use [Requests](http://docs.python-requests.org), rather than urllib? Requests does seem to be the way the Python community is going at present (and would allow us to standardize on a single dependency for Python HTTP integration).

**Comment by deltecent** [comment]
> Any chance we could split these into two separate PRs? The rdairplay(1) fix really belongs in 'master', not the 'rlm2' development branch.

Whoops... that's because I still stink at git. That change should have been in its own branch, but I messed up and was on master. I'll see what I can do.

> Daemonize? You don't find this a tad non-orthogonal, especially seeing as we will be adding a script management system?

I agree.

>How much work would it be to make this use Requests, rather than urllib? Requests does seem to be the way the Python community is going at present (and would allow us to standardize on a single dependency for Python HTTP integration).

I was trying to stick with stock installations and not require any dependencies. If having dependencies isn't an issue, yes, I can change it.

**Comment by ElvishArtisan** [comment]
I was thinking 'dependencies' more in the vein of *distro* dependencies. I generally try to avoid 'bleeding edge' libraries if I can avoid it. I've found that a good test is often to check to see if the latest RHEL distro (or the corresponding EPEL repo) has a package, as those sources are generally quite conservative. As it happens, Requests is in the Base repo for RHEL 7 (not the latest-and-greatest version I'm sure, but well-tested I'll bet). That makes it highly likely that it will be available as a native package (and hence easily available) on other platforms as well.

**Comment by deltecent** [comment]
> There's also [PycURL](http://pycurl.io/docs/latest/index.html) as well. A _much_ less Pythonic interface, but gives you all sorts of things beyond simple HTTP (FILE, FTP, SFTP, etc, etc). Writing a replacement for `rlm_urlwrite` will just about demand something like this.
> 
> Script writers are of course free to use any Python dependencies they choose. It's just for the ones that we're shipping with Rivendell itself that it would be good to standardize dependencies for.

I'm good with anything. I've never programmed in Python before, so I'll adapt to whatever you think is best.

**Comment by deltecent** [comment]
Fred, I've run into a problem with these that I can't figure out. The scripts run by themselves, and they seem to run if I run rdpadengined from the command line. They don't seem to run if rdpadengined is started with systemctl.

**Comment by ElvishArtisan** [comment]
Have you configured a system user for PyPAD scripts? rdpadengine(8) runs all scripts under the user/group defined in the new ```PypadOwner=``` and ```PypadGroup=``` directives in the ```[Identity]``` section of rd.conf(5). If those directives are missing, the scripts will run as 'nobody:nobody', which likely won't have the rights necessary to make things work as expected.

The standard installer will define these as follows:
```
PypadOwner=pypad
PypadGroup=pypad
```
and will create a 'pypad' user/group with a UID/GID of 151.

**Comment by deltecent** [comment]
You hit that one on the head. That's probably it. I built the system for it but neglected to update /etc/rd.conf. I'll give that a go.

Should we throw something in the log if those are missing in /etc/rd.conf?

**Comment by ElvishArtisan** [comment]
We could. Probably the better approach would be to have ```PypadOwner=``` and '''PypadGroup=``` return nonsense values (names that would be unlikely to exist on most systems. I vote for 'oobleck'). That in turn would make rdpadengined(8) fail at startup with a 'no such group' error when it attempted the ```setguid()```.

**Pull request closed without merging**
