### PR TITLE
Add section "Log Machines" to opsguide Chapter 11

### PR DESCRIPTION
**Pull request by dklann**
Overview description of the "mach" argument to macros that deal with log machines.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
In Rivendell 3.x, there are also 'virtual' log machines, which are numbered from 101 through 120. As the name implies, these are not bound to a GUI or rdairplay(1), but are available whenever the 'rivendell' service is active. They are controlled solely by RML, with configuration done in the 'Start/Stop Settings' and 'Log Mode Control' sections of RDAdmin->ManageHosts->RDAirPlay. They are implemented by the rdvairplayd(8) component, which is itself managed by rdservice(8).

**Comment by dklann** [comment]
Does log machine "0" refer to *all* log machines (1 through 120)? Or does it refer to all log machines in the "target" app (rdairplay [1 - 3] and rdvairplayd [101 - 120])?

**Comment by ElvishArtisan** [comment]
That's an excellent question, and one that it had not even occurred to me to consider. Using '0' will address log machines 1 - 3 --i.e. all log machines running on rdairplay(1). Virtual logs are unaffected.

(Now off to test to make sure it actually works that way...)  :)

**Comment by ElvishArtisan** [comment]
Merged to 'master'. Thank you!

NOTE: it's always Good Practice to append an appropriate entry to 'ChangeLog' in your PR. For example, something like:
```
2018-11-02 David Klann <dklann@linux.com>
	* Added a 'Log Machines' section to the 'Rivendell Macro Language'
	chapter of the Operations Guide.
```

**Comment by dklann** [comment]
Thanks for merging the PR. This was intended to be a "learning PR". I think I'm getting how it is supposed to work. I'll include a ChangeLog entry in the future. Do you prefer a "topic" branch for the PR as well? _Thank you_ for your continued work on this amazing system you have created!

**Pull request merged**
