### PR TITLE
Update loglinebox.cpp to support dark themes

### PR DESCRIPTION
**Pull request by danielbair**
Added support for dark themes.

### CODE REVIEW

**Comment by ElvishArtisan** [comment]
This does not appear to include any kind of 'configurability' that would allow users to choose whether to use this theme or not. Am I missing something?

**Comment by danielbair** [comment]
This allows the pass through of the system theme (dark or light).

**Comment by ElvishArtisan** [comment]
Please add a ```ChangeLog``` entry. (See the 'PULL REQUEST CHECKLIST' section in the 'CODINGSTYLE' file for details).

**Comment by danielbair** [comment]
Ok, Can you manually merge the ChangeLog entry? I hate trying to git rebase because it always gets messed up.

**Comment by ElvishArtisan** [comment]
> Can you manually merge the ChangeLog entry? 

No worries! That's SOP with ChangeLog entries.

**Comment by ElvishArtisan** [comment]
Merged to 'master' and 'qt5'. Thank you!

**Pull request merged**
